project:
  type: book

book:
  title: "Git Started With Open Source"
  author: "Fabio Rosado"
  date: "16/07/2022"
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - part: section-git.qmd
      chapters:
        - git-basics.qmd
    - part: section-opensource.qmd
      chapters:
        - opensource-basics.qmd
    - references.qmd
  appendices:
    - cheatsheet-git.qmd
    - cheatsheet-pr.qmd
  page-navigation: true
  page-footer:
    border: true
    left: "Copyright 2022, Fabio Rosado"
    right:
      - icon: github
        href: https://github.com/LandingInTech/gitstartedwithopensource
      - icon: twitter
        href: https://twitter.com/FabioRosado_
      - icon: instagram
        href: https://instagram.com/theflyingdev
  reader-mode: true
  repo-url: https://github.com/LandingInTech/gitstartedwithopensource
  repo-actions: [edit, issue]
  navbar:
    background: primary
    search: true

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: superhero
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
